---
antora:
  name: modules
  dir: www
  modules:
    - name: "module-01"
      label: "Overview"
      solveButton: false
    - name: "module-02"
      label: "CVEs"
      solveButton: false
    - name: "module-03"
      label: "Malware"
      solveButton: false
    - name: "module-04"
      label: "Advisor: Satellite"
      solveButton: false
    - name: "module-05"
      label: "Lightspeed Advisor in Satellite"
      solveButton: false
    - name: "module-06"
      label: "Conclusion"
      solveButton: false

tabs:
  - name: "Red Hat Hybrid Cloud Console"
    url: https://console.redhat.com
    external: true
  - name: "Satellite Web UI"
    url: https://satellite-${guid}.${domain}/
  - name: "satellite.lab terminal"
    url: /wetty_satellite/ssh/root
  - name: "rhel1.lab terminal"
    url: /wetty_rhel1/ssh/root
  - name: "rhel2.lab terminal"
    url: /wetty_rhel2/ssh/root
